import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Headers from "@/components/Headers";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/redux/ReduxProvider";
import ThemeApplier from "@/components/ThemeApplier";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        <ReduxProvider>
          <ThemeApplier />
          <main className="flex-col dark:bg-bg-dark">
            <Headers />
            <div className="p-12  mb-20">{children}</div>
            <Footer />
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
